/** Independent diagnostic dimensions; source coverage cannot prove deployed parity. */
const sourceCovered = {
  classification: "PRODUCTION_EXECUTION_SURFACE",
  writerBeforeExecution: true, startedBeforeParser: true, terminalEvents: true,
  executionIdPropagation: true, failClosed: true, deployedRelevant: true,
  sourceImplementation: "SOURCE_IMPLEMENTED", sourceOrdering: "SOURCE_IMPLEMENTED",
  syntheticProof: "SYNTHETIC_PROVEN", writerLiveDbProof: "LIVE_DB_VERIFIED",
  surfaceLiveExecutionProof: "UNKNOWN", liveDbProof: "UNKNOWN",
  deployedParity: "UNKNOWN", deployedRuntimeProof: "UNKNOWN",
  productionActivation: "BLOCKED", status: "BLOCKED",
} as const;
export const H3E91_R41_COVERAGE = {
  gate: "H.3-E.9.1-R4.1",
  status: "BLOCKED",
  writer: {
    present: true,
    version: 1,
    securityDefiner: true,
    searchPathEmpty: true,
    directTableWritesBlocked: true,
    writerLiveDbProof: "LIVE_DB_VERIFIED",
  },
  bridge: { protocol: "H3E91_EXECUTION_BRIDGE_V1", authenticatedExecutionEvents: true },
  lifecycle: {
    intent: true,
    started: true,
    finished: true,
    failed: true,
    aborted: true,
    idempotency: true,
    concurrency: true,
  },
  surfaces: {
    APP_REMOTE_PARSER: {
      ...sourceCovered,
    },
    RAILWAY_DURABLE_WORKER: {
      ...sourceCovered,
    },
    RAILWAY_V1_PARSE: {
      ...sourceCovered,
    },
    BROWSER_WASM_POC: {
      classification: "PRODUCTION_EXECUTION_SURFACE",
      writerBeforeExecution: false,
      startedBeforeParser: false,
      terminalEvents: false,
      executionIdPropagation: false,
      failClosed: false,
      deployedRelevant: true,
      sourceImplementation: "SOURCE_IMPLEMENTED", sourceOrdering: "SOURCE_IMPLEMENTED",
      syntheticProof: "SYNTHETIC_PROVEN", writerLiveDbProof: "LIVE_DB_VERIFIED",
      surfaceLiveExecutionProof: "UNKNOWN", liveDbProof: "UNKNOWN",
      deployedParity: "UNKNOWN", deployedRuntimeProof: "UNKNOWN",
      productionActivation: "BLOCKED", status: "BLOCKED",
    },
    REFERENCE_CLI: {
      classification: "TEST_ONLY",
      writerBeforeExecution: false,
      startedBeforeParser: false,
      terminalEvents: false,
      executionIdPropagation: false,
      failClosed: false,
      deployedRelevant: true,
      sourceImplementation: "SOURCE_IMPLEMENTED", sourceOrdering: "UNKNOWN",
      syntheticProof: "UNKNOWN", writerLiveDbProof: "LIVE_DB_VERIFIED",
      surfaceLiveExecutionProof: "UNKNOWN", liveDbProof: "UNKNOWN",
      deployedParity: "UNKNOWN", deployedRuntimeProof: "UNKNOWN",
      productionActivation: "BLOCKED",
      status: "IMAGE_EXCLUSION_SOURCE_ONLY",
    },
  },
  deployedParity: "UNKNOWN",
  ledgerAuthority: "UNINSTRUMENTED",
  writerCoverageVerified: false,
  blockers: [
    "H3E91_DEPLOYED_SOURCE_PARITY_UNKNOWN",
    "H3E91_DEPLOYED_BROWSER_BUNDLE_UNKNOWN",
    "H3E91_DEPLOYED_IMAGE_UNKNOWN",
  ],
} as const;
