/** Source-level R4.1 checkpoint. It is not an execution permit or ledger authority. */
export const H3E91_R41_COVERAGE = {
  gate: "H.3-E.9.1-R4.1",
  status: "BLOCKED",
  writer: {
    present: false,
    version: null,
    securityDefiner: false,
    searchPathEmpty: false,
    directTableWritesBlocked: true,
  },
  bridge: { protocol: null, authenticatedExecutionEvents: false },
  lifecycle: {
    intent: false,
    started: false,
    finished: false,
    failed: false,
    aborted: false,
    idempotency: false,
    concurrency: false,
  },
  surfaces: {
    APP_REMOTE_PARSER: {
      classification: "PRODUCTION_EXECUTION_SURFACE",
      writerBeforeExecution: false,
      startedBeforeParser: false,
      terminalEvents: false,
      executionIdPropagation: false,
      failClosed: false,
      deployedRelevant: true,
      status: "NOT_COVERED",
    },
    RAILWAY_DURABLE_WORKER: {
      classification: "PRODUCTION_EXECUTION_SURFACE",
      writerBeforeExecution: false,
      startedBeforeParser: false,
      terminalEvents: false,
      executionIdPropagation: false,
      failClosed: false,
      deployedRelevant: true,
      status: "NOT_COVERED",
    },
    RAILWAY_V1_PARSE: {
      classification: "PRODUCTION_EXECUTION_SURFACE",
      writerBeforeExecution: false,
      startedBeforeParser: false,
      terminalEvents: false,
      executionIdPropagation: false,
      failClosed: false,
      deployedRelevant: true,
      status: "NOT_COVERED",
    },
    BROWSER_WASM_POC: {
      classification: "PRODUCTION_EXECUTION_SURFACE",
      writerBeforeExecution: false,
      startedBeforeParser: false,
      terminalEvents: false,
      executionIdPropagation: false,
      failClosed: false,
      deployedRelevant: true,
      status: "NOT_COVERED",
    },
    REFERENCE_CLI: {
      classification: "TEST_ONLY",
      writerBeforeExecution: false,
      startedBeforeParser: false,
      terminalEvents: false,
      executionIdPropagation: false,
      failClosed: false,
      deployedRelevant: true,
      status: "IMAGE_EXCLUSION_SOURCE_ONLY",
    },
  },
  deployedParity: "UNKNOWN",
  ledgerAuthority: "UNINSTRUMENTED",
  writerCoverageVerified: false,
  blockers: [
    "H3E91_PREPARSER_WRITER_ABSENT",
    "H3E91_EXECUTION_SURFACE_NOT_COVERED",
    "H3E91_BROWSER_SURFACE_NOT_SEALED",
    "H3E91_REFERENCE_CLI_IMAGE_NOT_VERIFIED",
    "H3E91_DB_CONCURRENCY_UNTESTED",
    "H3E91_SECURITY_AUDIT_INCOMPLETE",
    "H3E91_DEPLOYED_SOURCE_PARITY_UNKNOWN",
  ],
} as const;
