REVOKE INSERT, UPDATE, DELETE, TRUNCATE, TRIGGER, REFERENCES ON public.h3e91_execution_evidence_ledger FROM PUBLIC, anon, authenticated, sandbox_exec, service_role;
ALTER TABLE public.h3e91_execution_evidence_ledger ALTER COLUMN job_id DROP NOT NULL, ALTER COLUMN attempt_number DROP NOT NULL, ALTER COLUMN demo_sha256 DROP NOT NULL, ALTER COLUMN file_size DROP NOT NULL, ALTER COLUMN parser_name DROP NOT NULL, ALTER COLUMN parser_version DROP NOT NULL, ALTER COLUMN parser_revision DROP NOT NULL, ALTER COLUMN metadata_digest DROP NOT NULL, ADD COLUMN event_digest text;
ALTER TABLE public.h3e91_execution_evidence_ledger ADD CONSTRAINT h3e91_event_digest_v1_format CHECK (event_id IS NULL OR event_digest ~ '^[0-9a-f]{64}$'), ADD CONSTRAINT h3e91_event_v1_required CHECK (event_id IS NULL OR (upload_id IS NOT NULL AND correlation_id IS NOT NULL AND execution_surface IS NOT NULL AND source IS NOT NULL AND (event_type = 'EXECUTION_INTENT' OR (parser_name IS NOT NULL AND parser_version IS NOT NULL AND parser_revision IS NOT NULL)) AND (event_type NOT IN ('EXECUTION_STARTED','EXECUTION_FINISHED','EXECUTION_FAILED') OR (demo_sha256 IS NOT NULL AND file_size IS NOT NULL)) AND ((event_type IN ('EXECUTION_FINISHED','EXECUTION_FAILED','EXECUTION_ABORTED')) = (outcome_code IS NOT NULL))));
CREATE UNIQUE INDEX h3e91_one_type_per_execution_v1 ON public.h3e91_execution_evidence_ledger(execution_id,event_type) WHERE execution_id IS NOT NULL;
CREATE UNIQUE INDEX h3e91_one_terminal_per_execution_v1 ON public.h3e91_execution_evidence_ledger(execution_id) WHERE execution_id IS NOT NULL AND event_type IN ('EXECUTION_FINISHED','EXECUTION_FAILED','EXECUTION_ABORTED');
CREATE FUNCTION public.h3e91_record_execution_event(_event_id uuid, _execution_id uuid, _event_type text, _upload_id uuid, _correlation_id uuid, _job_id uuid, _attempt_number integer, _demo_sha256 text, _file_size bigint, _parser_name text, _parser_version text, _parser_revision text, _execution_surface text, _source text, _metadata_digest text, _outcome_code text, _event_version integer) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $writer$
DECLARE _canonical text; _digest text; _same public.h3e91_execution_evidence_ledger%ROWTYPE; _prior public.h3e91_execution_evidence_ledger%ROWTYPE; _current public.h3e91_execution_evidence_ledger%ROWTYPE; _at timestamptz;
BEGIN
 IF _event_version IS DISTINCT FROM 1 THEN RETURN pg_catalog.jsonb_build_object('status','REJECTED','code','UNSUPPORTED_VERSION'); END IF;
 IF _execution_surface NOT IN ('APP_REMOTE_PARSER','RAILWAY_DURABLE_WORKER','RAILWAY_V1_PARSE') OR _execution_surface IS NULL THEN RETURN pg_catalog.jsonb_build_object('status','REJECTED','code','UNSUPPORTED_SURFACE'); END IF;
 IF (_execution_surface = 'APP_REMOTE_PARSER' AND _source IS DISTINCT FROM 'APP') OR (_execution_surface <> 'APP_REMOTE_PARSER' AND _source IS DISTINCT FROM 'RAILWAY') THEN RETURN pg_catalog.jsonb_build_object('status','REJECTED','code','UNSUPPORTED_SOURCE'); END IF;
 IF _event_id IS NULL OR _execution_id IS NULL OR _upload_id IS NULL OR _correlation_id IS NULL OR _event_type IS NULL OR _event_type NOT IN ('EXECUTION_INTENT','EXECUTION_STARTED','EXECUTION_FINISHED','EXECUTION_FAILED','EXECUTION_ABORTED') OR (_attempt_number IS NOT NULL AND _attempt_number < 1) OR (_file_size IS NOT NULL AND _file_size < 1) OR (_demo_sha256 IS NOT NULL AND _demo_sha256 !~ '^[0-9a-f]{64}$') OR (_metadata_digest IS NOT NULL AND _metadata_digest !~ '^[0-9a-f]{64}$') OR pg_catalog.length(pg_catalog.coalesce(_parser_name,'')) > 128 OR pg_catalog.length(pg_catalog.coalesce(_parser_version,'')) > 128 OR pg_catalog.length(pg_catalog.coalesce(_parser_revision,'')) > 128 THEN RETURN pg_catalog.jsonb_build_object('status','REJECTED','code','INVALID_INPUT'); END IF;
 IF (_event_type IN ('EXECUTION_FINISHED','EXECUTION_FAILED','EXECUTION_ABORTED')) AND (_outcome_code IS NULL OR _outcome_code !~ '^[A-Z][A-Z0-9_]{0,63}$') THEN RETURN pg_catalog.jsonb_build_object('status','REJECTED','code','OUTCOME_REQUIRED'); END IF;
 IF _event_type IN ('EXECUTION_INTENT','EXECUTION_STARTED') AND _outcome_code IS NOT NULL THEN RETURN pg_catalog.jsonb_build_object('status','REJECTED','code','OUTCOME_FORBIDDEN'); END IF;
 IF _event_type <> 'EXECUTION_INTENT' AND (pg_catalog.coalesce(pg_catalog.length(pg_catalog.btrim(_parser_name)),0) = 0 OR pg_catalog.coalesce(pg_catalog.length(pg_catalog.btrim(_parser_version)),0) = 0 OR pg_catalog.coalesce(pg_catalog.length(pg_catalog.btrim(_parser_revision)),0) = 0) THEN RETURN pg_catalog.jsonb_build_object('status','REJECTED','code','PARSER_IDENTITY_REQUIRED'); END IF;
 IF _event_type IN ('EXECUTION_STARTED','EXECUTION_FINISHED','EXECUTION_FAILED') AND (_demo_sha256 IS NULL OR _file_size IS NULL) THEN RETURN pg_catalog.jsonb_build_object('status','REJECTED','code','DEMO_IDENTITY_REQUIRED'); END IF;
 IF _event_type = 'EXECUTION_ABORTED' AND ((_demo_sha256 IS NULL) <> (_file_size IS NULL)) THEN RETURN pg_catalog.jsonb_build_object('status','REJECTED','code','DEMO_IDENTITY_REQUIRED'); END IF;
 -- Lock both identifiers in the same global order: event id then execution id. This serializes cross-execution event-id races.
 PERFORM pg_catalog.pg_advisory_xact_lock(39790, pg_catalog.hashtext(_event_id::text));
 PERFORM pg_catalog.pg_advisory_xact_lock(39791, pg_catalog.hashtext(_execution_id::text));
 _canonical := pg_catalog.jsonb_build_array(1,_event_id,_execution_id,_event_type,_upload_id,_correlation_id,_job_id,_attempt_number,_demo_sha256,_file_size,_parser_name,_parser_version,_parser_revision,_execution_surface,_source,_metadata_digest,_outcome_code)::text;
 _digest := pg_catalog.encode(extensions.digest(pg_catalog.convert_to(_canonical,'UTF8'),'sha256'),'hex');
 SELECT * INTO _same FROM public.h3e91_execution_evidence_ledger WHERE event_id = _event_id;
 IF FOUND THEN
  IF _same.event_digest = _digest THEN RETURN pg_catalog.jsonb_build_object('status','IDEMPOTENT_REPLAY','event_digest',_digest); END IF;
  RETURN pg_catalog.jsonb_build_object('status','REJECTED','code','EVENT_ID_CONFLICT');
 END IF;
 SELECT * INTO _same FROM public.h3e91_execution_evidence_ledger WHERE execution_id = _execution_id AND event_type = _event_type;
 IF FOUND THEN
  IF _same.event_digest = _digest THEN RETURN pg_catalog.jsonb_build_object('status','IDEMPOTENT_REPLAY','event_digest',_digest); END IF;
  RETURN pg_catalog.jsonb_build_object('status','REJECTED','code','TRANSITION_CONFLICT');
 END IF;
 SELECT * INTO _prior FROM public.h3e91_execution_evidence_ledger WHERE execution_id = _execution_id AND event_type = 'EXECUTION_INTENT';
 SELECT * INTO _current FROM public.h3e91_execution_evidence_ledger WHERE execution_id = _execution_id ORDER BY event_at DESC LIMIT 1;
 IF _event_type = 'EXECUTION_INTENT' AND _current.id IS NOT NULL OR _event_type <> 'EXECUTION_INTENT' AND _prior.id IS NULL OR _current.event_type IN ('EXECUTION_FINISHED','EXECUTION_FAILED','EXECUTION_ABORTED') OR _event_type = 'EXECUTION_STARTED' AND _current.event_type <> 'EXECUTION_INTENT' OR _event_type IN ('EXECUTION_FINISHED','EXECUTION_FAILED') AND _current.event_type <> 'EXECUTION_STARTED' OR _event_type = 'EXECUTION_ABORTED' AND _current.event_type NOT IN ('EXECUTION_INTENT','EXECUTION_STARTED') THEN RETURN pg_catalog.jsonb_build_object('status','REJECTED','code','INVALID_TRANSITION'); END IF;
 IF _prior.id IS NOT NULL AND (_prior.upload_id IS DISTINCT FROM _upload_id OR _prior.correlation_id IS DISTINCT FROM _correlation_id OR _prior.job_id IS DISTINCT FROM _job_id OR _prior.attempt_number IS DISTINCT FROM _attempt_number OR _prior.execution_surface IS DISTINCT FROM _execution_surface OR _prior.source IS DISTINCT FROM _source OR (_prior.demo_sha256 IS NOT NULL AND _prior.demo_sha256 IS DISTINCT FROM _demo_sha256) OR (_prior.file_size IS NOT NULL AND _prior.file_size IS DISTINCT FROM _file_size) OR (_prior.parser_name IS NOT NULL AND _prior.parser_name IS DISTINCT FROM _parser_name) OR (_prior.parser_version IS NOT NULL AND _prior.parser_version IS DISTINCT FROM _parser_version) OR (_prior.parser_revision IS NOT NULL AND _prior.parser_revision IS DISTINCT FROM _parser_revision)) THEN RETURN pg_catalog.jsonb_build_object('status','REJECTED','code','EXECUTION_IDENTITY_CONFLICT'); END IF;
 IF _current.id IS NOT NULL AND (_current.demo_sha256 IS NOT NULL AND _current.demo_sha256 IS DISTINCT FROM _demo_sha256 OR _current.file_size IS NOT NULL AND _current.file_size IS DISTINCT FROM _file_size OR _current.parser_name IS NOT NULL AND _current.parser_name IS DISTINCT FROM _parser_name OR _current.parser_version IS NOT NULL AND _current.parser_version IS DISTINCT FROM _parser_version OR _current.parser_revision IS NOT NULL AND _current.parser_revision IS DISTINCT FROM _parser_revision) THEN RETURN pg_catalog.jsonb_build_object('status','REJECTED','code','EXECUTION_IDENTITY_CONFLICT'); END IF;
 _at := pg_catalog.clock_timestamp();
 BEGIN
  INSERT INTO public.h3e91_execution_evidence_ledger(event_id,execution_id,event_type,event_at,upload_id,correlation_id,job_id,attempt_number,demo_sha256,file_size,parser_name,parser_version,parser_revision,execution_surface,source,metadata_digest,outcome_code,event_version,event_digest) VALUES (_event_id,_execution_id,_event_type,_at,_upload_id,_correlation_id,_job_id,_attempt_number,_demo_sha256,_file_size,_parser_name,_parser_version,_parser_revision,_execution_surface,_source,_metadata_digest,_outcome_code,1,_digest);
 EXCEPTION WHEN unique_violation THEN RETURN pg_catalog.jsonb_build_object('status','REJECTED','code','TRANSITION_CONFLICT'); END;
 RETURN pg_catalog.jsonb_build_object('status','INSERTED','event_digest',_digest);
END;
$writer$;
REVOKE ALL ON FUNCTION public.h3e91_record_execution_event(uuid,uuid,text,uuid,uuid,uuid,integer,text,bigint,text,text,text,text,text,text,text,integer) FROM PUBLIC,anon,authenticated,sandbox_exec;
GRANT EXECUTE ON FUNCTION public.h3e91_record_execution_event(uuid,uuid,text,uuid,uuid,uuid,integer,text,bigint,text,text,text,text,text,text,text,integer) TO service_role;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, TRIGGER, REFERENCES ON public.h3e91_execution_evidence_ledger FROM PUBLIC,anon,authenticated,sandbox_exec,service_role;